export const recipessMock = [
  {
    id: 1,
    name: 'coucous',
    nutrients_value: '360KCal',
    ingredients: ['semoule','tomates','sel','poivre','viande','pomme de terre','carrotes'],
    image:'http://www.weightwatchers-au-supermarche.fr/images/plat-coucous1.png',
    temps: '1h05',
    personnes: 4,
    etape1 : 'Etape 1\n' + 'Préparation de la semoule :\n' ,
    etape2 : 'Etape 2\n' + 'Verser la semoule dans un grand récipient et la noyer avec l\'eau. Remuer doucement.\n' ,
    etape3 :'Etape 3\n' + 'Égoutter la semoule quand l\'eau devient blanche\n' ,
    etape4 :'Etape 4\n' + 'Laisser reposer 15-20 mn (30 maxi), saler (1 cuillère à soupe rase), huiler (1 cuillère à soupe).\n' ,
    etape5 :'Etape 5\n' + 'Malaxer pour briser les mottes.\n' ,
    etape6 :'Etape 6\n' + 'Cuisson de la semoule :\n' ,
    etape7 :'Etape 7\n' + 'Dans une couscoussière de 5 litres, remplir à moitié d\'eau la partie basse et verser la semoule dans la partie haute (ne pas mettre de couvercle).\n' ,
    etape8 :'Etape 8\n' + 'Rendre hermétique si possible la couscoussière au niveau de la jonction des 2 parties afin d\'éviter l\'évaporation de la vapeur.\n' ,
    etape9 : 'Etape 9\n' + 'Compter une cuisson de 20 min à partir de l\'apparition de la vapeur à travers la semoule.\n' ,
    etape10 : 'Etape 10\n' + 'Verser la semoule dans un récipient, remuer doucement avec une cuillère en bois pour briser les mottes, ajouter 50 g de beurre et mélanger doucement.\n'
  },
  {
    id: 2,
    name: 'omlette',
    nutrients_value: '280KCal',
    ingredients: ['oeufs','sell','onions','frommage','thon'],
    image:'http://pngimg.com/uploads/omelette/omelette_PNG27.png',
    temps: '1h05',
    personnes: 4,
    etape1 : 'Etape 1\n' + 'Dans une poêle, faites dorer les lardons. Pendant qu\'ils bronzent, émincez l\'oignon et battez les oeufs.\n\n' ,
    etape2 : 'Etape 2\n' + 'Quand les lardons sont dorés, nettoyez grossièrement votre poêle, ajoutez l\'huile et faites revenir l\'oignon.\n' ,
    etape3 :'Etape 3\n' + 'Quand l\'oignon est légèrement coloré, vous pouvez alors rajouter vos pâtes, les lardons.\n\n' ,
    etape4 :'Etape 4\n' + 'Salez, poivrez, mélangez délicatement et laissez les arômes s\'échanger entre les aliments, puis versez l\'oeuf battu en omelette.\n' ,
    etape5 :'Etape 5\n' + 'Patientez quelques minutes, et dégustez.\n\n' ,

  },
  {
    id: 3,
    name: 'pizza',
    nutrients_value: '520KCal',
    ingredients: ['oeufs','sell','onions','frommage','thon','poivron', 'pimon', 'pattes', 'huile' , 'olives'],
    image:'https://www.pngarts.com/files/3/Pizza-PNG-Photo.png',
    temps: '1h05',
    personnes: 4,
    etape1 : 'Etape 1\n' + 'Pelez et hachez les oignons et l\'ail. Pelez et épépinez les tomates, découpez-les en dés.\n\n' ,
    etape2 : 'Etape 2\n' + 'VFaites chauffer 2 cuillères à soupe d\'huile d\'olive. Mettez-les l\'ail et l\'oignon, laissez-les dorer. RAjoutez les tomates, salez, poivrez et ajoutez le thym.\n' ,
    etape3 :'Etape 3\n' + 'Laissez cuire 20 minutes à feu moyen, jusqu\'à ce que le liquide soit évaporé.' ,
    etape4 :'Etape 4\n' + 'Laisser reposer 15-20 mn (30 maxi), saler (1 cuillère à soupe rase), huiler (1 cuillère à soupe).\n' ,
    etape5 :'Etape 5\n' + 'Malaxer pour briser les mottes.\n' ,
    etape6 :'Etape 6\n' + 'Cuisson de la semoule :\n' ,
    etape7 :'Etape 7\n' + 'Dans une couscoussière de 5 litres, remplir à moitié d\'eau la partie basse et verser la semoule dans la partie haute (ne pas mettre de couvercle).\n' ,
    etape8 :'Etape 8\n' + 'Rendre hermétique si possible la couscoussière au niveau de la jonction des 2 parties afin d\'éviter l\'évaporation de la vapeur.\n' ,
    etape9 : 'Etape 9\n' + 'Compter une cuisson de 20 min à partir de l\'apparition de la vapeur à travers la semoule.\n' ,
    etape10 : 'Etape 10\n' + 'Verser la semoule dans un récipient, remuer doucement avec une cuillère en bois pour briser les mottes, ajouter 50 g de beurre et mélanger doucement.\n'
  },
  {
    id: 3,
    name: 'riz',
    nutrients_value: '520KCal',
    ingredients: ['oeufs','sell','onions','frommage','thon','poivron', 'pimon', 'pattes', 'huile' , 'olives'],
    image:'http://www.weightwatchers-au-supermarche.fr/images/plat-blanquette-poulet2.png',
    temps: '1h05',
    personnes: 4,
    etape1 : 'Etape 1\n' + 'Préparation de la semoule :\n' ,
    etape2 : 'Etape 2\n' + 'Verser la semoule dans un grand récipient et la noyer avec l\'eau. Remuer doucement.\n' ,
    etape3 :'Etape 3\n' + 'Égoutter la semoule quand l\'eau devient blanche\n' ,
    etape4 :'Etape 4\n' + 'Laisser reposer 15-20 mn (30 maxi), saler (1 cuillère à soupe rase), huiler (1 cuillère à soupe).\n' ,
    etape5 :'Etape 5\n' + 'Malaxer pour briser les mottes.\n' ,
    etape6 :'Etape 6\n' + 'Cuisson de la semoule :\n' ,
    etape7 :'Etape 7\n' + 'Dans une couscoussière de 5 litres, remplir à moitié d\'eau la partie basse et verser la semoule dans la partie haute (ne pas mettre de couvercle).\n' ,
    etape8 :'Etape 8\n' + 'Rendre hermétique si possible la couscoussière au niveau de la jonction des 2 parties afin d\'éviter l\'évaporation de la vapeur.\n' ,
    etape9 : 'Etape 9\n' + 'Compter une cuisson de 20 min à partir de l\'apparition de la vapeur à travers la semoule.\n' ,
    etape10 : 'Etape 10\n' + 'Verser la semoule dans un récipient, remuer doucement avec une cuillère en bois pour briser les mottes, ajouter 50 g de beurre et mélanger doucement.\n'
  },
  {
    id: 4,
    name: 'lasagnes',
    nutrients_value: '120KCal',
    ingredients: ['pates','sel','onions','fromage','tomates','poivrons', 'piments', 'viande hachée '],
    image:'http://cdn.shopify.com/s/files/1/1071/8616/products/Lasagne-Bolognese-cutout_grande.png?v=1535349576',
    temps: '1h05',
    personnes: 4,
    etape1 : 'Etape 1\n' + 'Préparation de la semoule :\n' ,
    etape2 : 'Etape 2\n' + 'Verser la semoule dans un grand récipient et la noyer avec l\'eau. Remuer doucement.\n' ,
    etape3 :'Etape 3\n' + 'Égoutter la semoule quand l\'eau devient blanche\n' ,
    etape4 :'Etape 4\n' + 'Laisser reposer 15-20 mn (30 maxi), saler (1 cuillère à soupe rase), huiler (1 cuillère à soupe).\n' ,
    etape5 :'Etape 5\n' + 'Malaxer pour briser les mottes.\n' ,
    etape6 :'Etape 6\n' + 'Cuisson de la semoule :\n' ,
    etape7 :'Etape 7\n' + 'Dans une couscoussière de 5 litres, remplir à moitié d\'eau la partie basse et verser la semoule dans la partie haute (ne pas mettre de couvercle).\n' ,
    etape8 :'Etape 8\n' + 'Rendre hermétique si possible la couscoussière au niveau de la jonction des 2 parties afin d\'éviter l\'évaporation de la vapeur.\n' ,
    etape9 : 'Etape 9\n' + 'Compter une cuisson de 20 min à partir de l\'apparition de la vapeur à travers la semoule.\n' ,
    etape10 : 'Etape 10\n' + 'Verser la semoule dans un récipient, remuer doucement avec une cuillère en bois pour briser les mottes, ajouter 50 g de beurre et mélanger doucement.\n'
  },
  {
    id: 5,
    name: 'soupe',
    nutrients_value: '420KCal',
    ingredients: ['tomate','sel','thon','grain','tomate','poivron', 'huile', 'piment rouge'],
    image:'https://www.edwards-sandwiches.ch/278-large_default/soupe-du-jour.jpg',
    temps: '1h05',
    personnes: 4,
    etape1 : 'Etape 1\n' + 'Préparation de la semoule :\n' ,
    etape2 : 'Etape 2\n' + 'Verser la semoule dans un grand récipient et la noyer avec l\'eau. Remuer doucement.\n' ,
    etape3 :'Etape 3\n' + 'Égoutter la semoule quand l\'eau devient blanche\n' ,
    etape4 :'Etape 4\n' + 'Laisser reposer 15-20 mn (30 maxi), saler (1 cuillère à soupe rase), huiler (1 cuillère à soupe).\n' ,
    etape5 :'Etape 5\n' + 'Malaxer pour briser les mottes.\n' ,
    etape6 :'Etape 6s\n' + 'Cuisson de la semoule :\n' ,
    etape7 :'Etape 7\n' + 'Dans une couscoussière de 5 litres, remplir à moitié d\'eau la partie basse et verser la semoule dans la partie haute (ne pas mettre de couvercle).\n' ,
    etape8 :'Etape 8\n' + 'Rendre hermétique si possible la couscoussière au niveau de la jonction des 2 parties afin d\'éviter l\'évaporation de la vapeur.\n' ,
    etape9 : 'Etape 9\n' + 'Compter une cuisson de 20 min à partir de l\'apparition de la vapeur à travers la semoule.\n' ,
    etape10 : 'Etape 10\n' + 'Verser la semoule dans un récipient, remuer doucement avec une cuillère en bois pour briser les mottes, ajouter 50 g de beurre et mélanger doucement.\n'
  },

  ];
